### ISSUE TITLE
Script will not run on Linux Mint

### ISSUE THREAD

**Issue by cydnax** [patrick-atgithub/joplintool#1]
andy@andy-HP:~/Downloads/joplintool-master$ ./joplintool.py --checkresources
./joplintool.py: line 3: $'\r': command not found
./joplintool.py: line 4: import: command not found
./joplintool.py: line 5: $'\r': command not found
./joplintool.py: line 6: $'try:\r': command not found
./joplintool.py: line 7: import: command not found
./joplintool.py: line 8: $'except:\r': command not found
./joplintool.py: line 9: syntax error near unexpected token `'needs python3... sorry ''
'/joplintool.py: line 9: `    print('needs python3... sorry ')

**Comment by patrick-atgithub** [comment]
did you try to start the script with the python interpreter ?:
`python ./joplintool.py --checkresources`
